apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hj9cvonf9-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hj9cvonf9-java-quarkus-gitops